title: PYeonju's Blog
description: 게임 서버 개발 기록
author_name: PYeonju
url: https://pyeonju.github.io
baseurl: ""
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

timezone: Asia/Seoul
